// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ6Wzktm2GrmIeaGkK8bAoYLfahutL7Ow',
    appId: '1:541728671061:web:67b57b774e5e961c60dbdc',
    messagingSenderId: '541728671061',
    projectId: 'buy-it-eed95',
    authDomain: 'buy-it-eed95.firebaseapp.com',
    storageBucket: 'buy-it-eed95.firebasestorage.app',
    measurementId: 'G-8N8EVV78WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCyWvCvbGUAinFZlUY45sIwP51QXgB9q8',
    appId: '1:541728671061:android:df3da18e55ba657560dbdc',
    messagingSenderId: '541728671061',
    projectId: 'buy-it-eed95',
    storageBucket: 'buy-it-eed95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1g_5P6d4RqxSnENw3xRt2HFs1_eIKos',
    appId: '1:541728671061:ios:cf20eb9b7e44b3a860dbdc',
    messagingSenderId: '541728671061',
    projectId: 'buy-it-eed95',
    storageBucket: 'buy-it-eed95.firebasestorage.app',
    iosBundleId: 'com.example.buyIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW1g_5P6d4RqxSnENw3xRt2HFs1_eIKos',
    appId: '1:541728671061:ios:cf20eb9b7e44b3a860dbdc',
    messagingSenderId: '541728671061',
    projectId: 'buy-it-eed95',
    storageBucket: 'buy-it-eed95.firebasestorage.app',
    iosBundleId: 'com.example.buyIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ6Wzktm2GrmIeaGkK8bAoYLfahutL7Ow',
    appId: '1:541728671061:web:87146d79fa65a23460dbdc',
    messagingSenderId: '541728671061',
    projectId: 'buy-it-eed95',
    authDomain: 'buy-it-eed95.firebaseapp.com',
    storageBucket: 'buy-it-eed95.firebasestorage.app',
    measurementId: 'G-XXYEB5LG91',
  );
}
